chore(github-action): Avoid builds for pushes to docs and changelog directories
openebs/lvm-localpv pull request #42
Opened 2021-04-07 10:32 UTC by niladrih

Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>

The build.yml and pull_request.yml workflows will ignore pushes made to `docs/` and `changelogs/` directories. This will result in images not built for pushes made to above directories.

2021-04-07 14:18 UTC, niladrih commented
Related PRs:
https://github.com/openebs/node-disk-manager/pull/562
https://github.com/openebs/cstor-operators/pull/271
https://github.com/openebs/dynamic-localpv-provisioner/pull/41
https://github.com/openebs/zfs-localpv/pull/306
https://github.com/openebs/jiva-operator/pull/66
https://github.com/openebs/maya/pull/1797
https://github.com/openebs/cstor-csi/pull/151
https://github.com/openebs/jiva/pull/350
https://github.com/openebs/libcstor/pull/85
https://github.com/openebs/velero-plugin/pull/151
https://github.com/openebs/m-exporter/pull/14

2021-04-28 13:48 UTC, akhilerm commented on .github/workflows/build.yml
> +      # - 'deploy/helm/**'
Why is `deploy/helm` commented out?

2021-04-28 13:49 UTC, akhilerm commented on .github/workflows/pull_request.yml
> +      # - 'deploy/helm/**'
same comment as above.

2021-04-28 13:49 UTC, akhilerm approved these changes
LGTM

2021-04-28 13:52 UTC, akhilerm requested changes
In release workflow tag also needs to be mentioned.

2021-04-28 13:52 UTC, akhilerm commented on .github/workflows/release.yml
The tags also needs to be mentioned here.

2021-04-28 14:21 UTC, akhilerm approved these changes
LGTM

2021-05-04 10:57 UTC, shubham14bajpai approved these changes
LGTM

2021-05-05 05:18 UTC, akhilerm approved these changes
LGTM

2021-05-05 05:19 UTC, merged

2021-05-05 05:26 UTC, akhilerm commented
@kmova Can you add the the QUAY token to this repo. I merged this directly after approving. After adding the QUAY token, will re-run the build.