doc(storageclass): add docs for custom node labels
openebs/lvm-localpv pull request #43
Opened 2021-04-11 07:57 UTC by akhilerm

- add docs for custom node labels in storage class

Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>

2021-04-11 13:44 UTC, w3aman requested changes

2021-04-11 13:44 UTC, w3aman commented on docs/storageclasses.md
> +
there is no FAQ path

2021-04-12 04:57 UTC, akhilerm commented on docs/storageclasses.md
> +
Done @w3aman

2021-04-14 09:53 UTC, pawanpraka1 approved these changes
looks good.

2021-04-14 09:54 UTC, merged